language: python

python:
  - pypy
  - 2.7
  - 3.5
  - 3.6
#  - 3.7

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install: pip install .

script: python setup.py nosetests

