#!/bin/sh

mkdir -p docs/_static docs/_build
sphinx-build -E -b html docs/ docs/_build || exit 1
if [ "$1" = "publish" ] ; then
  cd docs/
  echo "Uploading files..."
  scp -r _build/* ianbicking@web.sf.net:/home/groups/f/fo/formencode/htdocs/
fi
