#!/bin/sh

case "$1"
    in
    mo)
        echo "Regenerating all .mo files"
        for F in `find . -name '*.po'` ; do
            DEST="`basename $F .po`.mo"
            echo msgfmt "$F" -o "$DEST"
        done
        ;;
    gettext)
        FILES="formencode/api.py formencode/compound.py formencode/fieldstorage.py
               formencode/foreach.py formencode/national.py formencode/schema.py
               formencode/validators.py"
        echo pygettext $FILES --output=formencode/i18n/FormEncode.pot
        ;;
    *)
        echo "Error: unknown command $1"
        echo "Usage: `basename $0` mo | gettext"
        exit 2
        ;;
esac
