#!/bin/sh
cd `dirname $0`
for FN in *.txt ; do
    NAME=`basename $FN .txt`
    if [ -e "$NAME.html" -a ! "$NAME.html" -ot "$NAME.txt" ] ; then
        echo "$NAME is up to date."
        continue
    fi
    echo "Building $NAME."
    rst2html.py "$NAME.txt" > "$NAME.html"
done
